SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS portfolio_projects (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(190) NOT NULL,
    slug VARCHAR(190) NOT NULL,
    status ENUM('draft','active','archived') NOT NULL DEFAULT 'draft',
    featured TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 100,
    project_url VARCHAR(500) NULL,
    project_url_label VARCHAR(120) NOT NULL DEFAULT 'View project',
    client_name VARCHAR(190) NULL,
    project_type VARCHAR(190) NULL,
    industry VARCHAR(190) NULL,
    year_label VARCHAR(80) NULL,
    role_title VARCHAR(255) NULL,
    services TEXT NULL,
    technologies TEXT NULL,
    summary TEXT NULL,
    overview MEDIUMTEXT NULL,
    challenge MEDIUMTEXT NULL,
    solution MEDIUMTEXT NULL,
    results MEDIUMTEXT NULL,
    keywords TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_portfolio_projects_slug (slug),
    KEY idx_portfolio_projects_public (status,featured,sort_order,published_at),
    CONSTRAINT fk_portfolio_projects_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_portfolio_projects_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS portfolio_media (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    project_id BIGINT UNSIGNED NOT NULL,
    media_role ENUM('cover','gallery') NOT NULL DEFAULT 'gallery',
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    width_px INT UNSIGNED NULL,
    height_px INT UNSIGNED NULL,
    alt_text VARCHAR(500) NULL,
    caption VARCHAR(500) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_portfolio_media_stored_name (stored_name),
    KEY idx_portfolio_media_project_role (project_id,media_role,sort_order,id),
    CONSTRAINT fk_portfolio_media_project
        FOREIGN KEY (project_id) REFERENCES portfolio_projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_portfolio_media_created_by
        FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO portfolio_projects (
    title,slug,status,featured,sort_order,project_url,project_url_label,
    client_name,project_type,industry,year_label,role_title,
    services,technologies,summary,overview,challenge,solution,results,
    keywords,published_at
) VALUES
(
    'Gruber Procurement Intelligence Platform',
    'gruber',
    'active',
    1,
    10,
    'https://northmountainmedia.com/gruber',
    'View the Gruber platform',
    'Self-directed portfolio demonstration',
    'Procurement Intelligence Platform',
    'Procurement and multi-company operations',
    '2026',
    'Product strategy, workflow architecture, interface design and implementation',
    'Opportunity analysis\nWorkflow mapping\nInformation architecture\nInterface design\nPHP/MySQL implementation\nQuality assurance',
    'PHP\nMySQL\nProcurement workflows\nSupplier data\nInventory\nExecutive reporting\nHuman-supervised AI',
    'A connected procurement operating environment that turns fragmented supplier, SKU, inventory, purchasing, approval and savings information into a shared decision-ready system.',
    'The platform brings supplier records, item and SKU masters, purchase orders, inventory snapshots, savings opportunities, scorecards, approvals, audit history and executive reporting into one shared environment.',
    'Purchasing information can become fragmented across companies, departments, spreadsheets, supplier records, item masters, inventory systems, approvals and reporting. This makes savings opportunities, supplier risk, data quality and next actions harder to see.',
    'A connected procurement environment with shared masters, purchase orders, inventory snapshots, savings tracking, supplier scorecards, approvals, audit history, executive reporting and human-supervised AI assistance.',
    'A working portfolio demonstration showing how procurement teams could operate from a more visible, accountable and decision-ready system. It is a self-directed demonstration rather than a claimed deployed Gruber production system.',
    'gruber\nprocurement\nsupplier management\npurchase orders\ninventory\nsavings\nscorecards\nbusiness intelligence',
    UTC_TIMESTAMP()
),
(
    'Microgifter',
    'microgifter',
    'active',
    1,
    20,
    'https://microgifter.com/',
    'View Microgifter',
    'Microgifter',
    'Social Gifting and Merchant CRM Platform',
    'Hospitality, local commerce and customer engagement',
    '2024–Present',
    'Founder, product architect and systems builder',
    'Product strategy\nMerchant CRM\nSocial gifting\nCampaign architecture\nLifecycle design\nUI/UX\nPHP/MySQL\nQA and release planning',
    'PHP\nMySQL\nJavaScript\nMerchant CRM\nCampaign automation\nGift lifecycle tracking\nAgent-assisted commerce',
    'A mobile-first social-gifting, merchant CRM, loyalty, campaign, claim and automated-commerce platform designed to make local gifting easier.',
    'Microgifter connects gift certificates and product gifting with merchant CRM records, campaigns, offers, rewards, referrals, customer messaging, claim and redemption tracking, recurring programs and agent-assisted commerce.',
    'Local customers often fall back on national brands because independent business gifts are difficult to discover, purchase, send and manage. Merchants also do not want more hardware or disconnected marketing, loyalty, CRM and redemption systems.',
    'One connected mobile-first platform for social gifting, merchant CRM, campaigns, rewards, referrals, messaging, claims, redemption and automated commerce.',
    'A functional and continually expanding platform demonstrating how local gifting can become a measurable customer-lifecycle and commerce system rather than a standalone gift certificate.',
    'microgifter\nsocial gifting\nmerchant crm\nloyalty\ncampaigns\nclaims\nredemption\nautomated commerce',
    UTC_TIMESTAMP()
),
(
    'Homestead',
    'homestead',
    'active',
    0,
    30,
    'https://github.com/bigriversocial74/foodfarm',
    'View Homestead repository',
    'North Mountain Media',
    'Household Food Operating System',
    'Household operations and sustainable domestic agriculture',
    '2026',
    'Product concept, requirements, data architecture, privacy and QA',
    'Product requirements\nData modeling\nHousehold workflows\nPrivacy architecture\nInterface direction\nPhased delivery\nRepository QA',
    'PHP\nMySQL\nHousehold permissions\nInventory ledgers\nForecasting\nNotifications\nShared calendar',
    'A household food operating system connecting family access, pantry inventory, recipes, meals, gardens, harvests, preservation, shopping, tasks, forecasting, costs, nutrition and alerts.',
    'Homestead organizes the complete domestic food lifecycle through connected household records instead of isolated pantry lists, recipes, garden schedules and shopping notes.',
    'Household food management is fragmented across recipes, pantry lists, shopping notes, garden schedules, preservation records, family responsibilities, budgets and calendars.',
    'One lifecycle-based system connecting members, inventory, recipes, prepared food, meals, gardens, harvests, preservation, shopping, tasks, forecasts, costs, nutrition planning, alerts and calendar activity.',
    'A multi-phase PHP/MySQL application with household isolation, transactional workflows, provenance, idempotency, protected health checks and an expanding operational feature set.',
    'homestead\nfoodfarm\npantry\ngarden\npreservation\nfamily operations\nforecasting\nhousehold system',
    UTC_TIMESTAMP()
),
(
    'Poolzebo',
    'poolzebo',
    'active',
    0,
    40,
    'https://northmountainmedia.com/pool',
    'View Poolzebo',
    'North Mountain Media',
    'Modular Product and Outdoor-Living System',
    'Outdoor living, modular construction and direct sales',
    '2026',
    'Concept development, product-system design, positioning and web experience',
    'Product concept\nModular configuration\nBrand positioning\nExperience design\nWeb design\nSales presentation',
    'PHP\nResponsive web design\nProduct visualization\nModular configuration\nLead generation',
    'A modular backyard pool-and-deck system combining repeatable kit models with larger custom outdoor-living configurations.',
    'Poolzebo is designed around the complete backyard experience rather than a standalone deck or gazebo. Smaller versions can work as repeatable kit models while larger builds can add extended roofs, lounges, bars and different pool placements.',
    'Traditional backyard pool, deck and gazebo purchases are fragmented across contractors, components, planning and installation decisions.',
    'A coordinated modular product system that packages pool, deck, shade, lounge and optional bar experiences into clearer kit and custom configurations.',
    'A differentiated product and brand concept with a direct positioning idea: vacation starts in the backyard.',
    'poolzebo\npool deck\nmodular backyard\noutdoor living\nkit system\ncustom pool',
    UTC_TIMESTAMP()
),
(
    'Spaced Invaders',
    'spaced-invaders',
    'active',
    0,
    50,
    'https://northmountainmedia.com/space',
    'Play Spaced Invaders',
    'North Mountain Media',
    'Browser Strategy and Defense Game',
    'Interactive entertainment and game systems',
    '2026',
    'Game concept, systems design, interface direction and simulation logic',
    'Game design\nSimulation systems\nEnemy intelligence\nDefense balancing\nInterface design\nProgression design',
    'PHP\nJavaScript\nBrowser simulation\nGame-state systems\nResponsive UI',
    'A browser-based settlement defense game featuring intelligent UFO attacks, missile defenses, drone swarms, captures, settlement progression and operational command views.',
    'Spaced Invaders combines settlement management with a live alien-defense simulation. UFOs maneuver around defenses, require multiple hits, launch drone swarms and create persistent settlement outcomes.',
    'Simple invader games often rely on predictable movement and disconnected scorekeeping, which limits strategy and long-term progression.',
    'A richer simulation with adaptive UFO behavior, layered defenses, settlement-level statistics, capture systems, command feeds and tabbed operational views.',
    'A playable game concept demonstrating interactive systems design, state tracking, balancing, responsive interface work and iterative simulation refinement.',
    'spaced invaders\nbrowser game\nufo\nsettlement defense\nmissile defense\ndrone swarm\ngame systems',
    UTC_TIMESTAMP()
),
(
    'Stonefellow',
    'stonefellow',
    'active',
    0,
    60,
    'https://stonefellow.com/',
    'View Stonefellow',
    'Ganjafesto Records',
    'Membership, Streaming and Entertainment Platform',
    'Music, episodic media and direct-to-fan commerce',
    '2026',
    'Entertainment product design, brand direction, streaming UX and commerce architecture',
    'Entertainment branding\nMembership architecture\nMusic streaming UX\nEpisode design\nMerchandise commerce\nAuthentication and checkout',
    'PHP\nMySQL\nJavaScript\nStreaming interfaces\nMembership\nEcommerce',
    'A membership and streaming platform for original music, episodic media, merchandise, playlists and direct fan relationships.',
    'Stonefellow combines a public subscription site, music previews, member streaming, playlists, albums, episodic content, cast and series pages, merchandise, authentication, cart and checkout.',
    'Independent entertainment properties often split music, episodes, membership, merchandise and audience relationships across unrelated platforms.',
    'One branded entertainment environment connecting subscription access, streaming, episodic storytelling, cast information, playlists, merchandise and direct fan commerce.',
    'A working product direction demonstrating entertainment branding, audience ownership, content architecture, subscriptions, ecommerce and media-product interface design.',
    'stonefellow\nmusic streaming\nmembership\nepisodes\nmerchandise\ndirect to fan\nentertainment platform',
    UTC_TIMESTAMP()
),
(
    'Roger Huston',
    'roger-huston',
    'active',
    0,
    70,
    'https://rogerhuston.com/',
    'View Roger Huston',
    'Ganjafesto Records',
    'Artist Portfolio and Direct-to-Fan Commerce',
    'Music, visual art and creator commerce',
    '2025–Present',
    'Artist, producer, designer, product architect and ecommerce builder',
    'Songwriting\nMusic production\nGraphic design\nArtist branding\nDirect-to-fan commerce\nCustom product design\nKnowledge-agent strategy',
    'Reaper\nMusic production\nPrint-on-demand\nEcommerce\nCustom vinyl\nKnowledge agent',
    'An artist-commerce environment connecting Space Reggae music, visual art, personalized products, fulfillment, affiliates and conversational engagement.',
    'Roger Huston extends beyond a traditional artist site by connecting music discovery, graphic artwork, streaming links, print-on-demand products, personalized vinyl records, affiliate-assisted configuration, publishing and an artist knowledge agent.',
    'Independent music sites often stop at streaming links or basic merchandise, leaving artist identity, visual work, personalized fan products, customer service and conversational engagement disconnected.',
    'A broader creative-commerce environment combining music, visual art, merchandise, custom vinyl, affiliates, Ganjafesto Records and an artist knowledge agent.',
    'A working demonstration of how an independent creator can turn a music catalog into a connected brand, commerce, personalization, publishing and conversational-media system.',
    'roger huston\nspace reggae\nartist commerce\ncustom vinyl\nmusic production\nvisual art\ndirect to fan',
    UTC_TIMESTAMP()
)
ON DUPLICATE KEY UPDATE
    title=VALUES(title),
    status=VALUES(status),
    featured=VALUES(featured),
    sort_order=VALUES(sort_order),
    project_url=VALUES(project_url),
    project_url_label=VALUES(project_url_label),
    client_name=VALUES(client_name),
    project_type=VALUES(project_type),
    industry=VALUES(industry),
    year_label=VALUES(year_label),
    role_title=VALUES(role_title),
    services=VALUES(services),
    technologies=VALUES(technologies),
    summary=VALUES(summary),
    overview=VALUES(overview),
    challenge=VALUES(challenge),
    solution=VALUES(solution),
    results=VALUES(results),
    keywords=VALUES(keywords),
    published_at=COALESCE(published_at,VALUES(published_at));
