<?php
/* North Mountain Media build: 20260727-visual-site-builder-v61 */
declare(strict_types=1);
require_once __DIR__.'/visitor-intelligence.php';

function site_analytics_music_events(int $days): array
{
    if(!visitor_intelligence_schema_available())return[];$threshold=(new DateTimeImmutable('-'.$days.' days'))->format('Y-m-d H:i:s');$s=db()->prepare('SELECT event_type,event_label,metadata_json,duration_seconds,occurred_at,visitor_id,session_id,page_path FROM visitor_events WHERE occurred_at>=:threshold AND event_type LIKE "music_%" ORDER BY occurred_at DESC LIMIT 10000');$s->execute(['threshold'=>$threshold]);return$s->fetchAll();
}
function site_analytics_render_admin(): void
{
    $days=max(7,min(365,query_int('days',30)));$threshold=(new DateTimeImmutable('-'.$days.' days'))->format('Y-m-d H:i:s');$totals=['events'=>0,'visitors'=>0,'sessions'=>0,'page_views'=>0,'conversions'=>0];$topPages=[];$music=site_analytics_music_events($days);
    if(visitor_intelligence_schema_available()){
        $s=db()->prepare('SELECT COUNT(*) events,COUNT(DISTINCT visitor_id) visitors,COUNT(DISTINCT session_id) sessions,SUM(event_type IN ("page_view","builder_page_view")) page_views,SUM(event_type LIKE "%submitted" OR event_type LIKE "%accepted" OR event_type LIKE "%conversion%") conversions FROM visitor_events WHERE occurred_at>=:threshold');$s->execute(['threshold'=>$threshold]);$totals=array_merge($totals,$s->fetch()?:[]);
        $s=db()->prepare('SELECT page_path,COUNT(*) views,COUNT(DISTINCT visitor_id) visitors FROM visitor_events WHERE occurred_at>=:threshold AND event_type IN ("page_view","builder_page_view") GROUP BY page_path ORDER BY views DESC LIMIT 12');$s->execute(['threshold'=>$threshold]);$topPages=$s->fetchAll();
    }
    $musicTotals=['starts'=>0,'completions'=>0,'pauses'=>0,'resumes'=>0,'skips'=>0,'listeners'=>[],'sessions'=>[],'seconds'=>0];$tracks=[];$albums=[];$engagement=[];
    foreach($music as $event){$type=(string)$event['event_type'];if(in_array($type,['music_track_started','music_track_play'],true))$musicTotals['starts']++;elseif($type==='music_track_completed')$musicTotals['completions']++;elseif($type==='music_track_paused')$musicTotals['pauses']++;elseif($type==='music_track_resumed')$musicTotals['resumes']++;elseif($type==='music_track_skipped')$musicTotals['skips']++;$musicTotals['listeners'][(int)$event['visitor_id']]=true;$musicTotals['sessions'][(int)$event['session_id']]=true;$meta=visitor_intelligence_metadata_decode($event['metadata_json']??null);$track=(string)($event['event_label']??$meta['track_title']??'Unknown track');$trackId=(string)($meta['track_id']??$track);$position=max((int)($event['duration_seconds']??0),(int)($meta['position_seconds']??0));$engagementKey=(int)$event['session_id'].'|'.$trackId;$engagement[$engagementKey]=max($engagement[$engagementKey]??0,$position);$tracks[$track]??=['title'=>$track,'starts'=>0,'completions'=>0,'skips'=>0,'seconds'=>0];if(in_array($type,['music_track_started','music_track_play'],true))$tracks[$track]['starts']++;if($type==='music_track_completed')$tracks[$track]['completions']++;if($type==='music_track_skipped')$tracks[$track]['skips']++;$tracks[$track]['seconds']=max($tracks[$track]['seconds'],$position);$album=(string)($meta['album_title']??'Singles and uncategorized');$albums[$album]??=['title'=>$album,'starts'=>0,'completions'=>0];if(in_array($type,['music_track_started','music_track_play'],true))$albums[$album]['starts']++;if($type==='music_track_completed')$albums[$album]['completions']++;}
    $musicTotals['seconds']=array_sum($engagement);usort($tracks,static fn($a,$b)=>$b['starts']<=>$a['starts']);usort($albums,static fn($a,$b)=>$b['starts']<=>$a['starts']);$completionRate=$musicTotals['starts']>0?round(($musicTotals['completions']/$musicTotals['starts'])*100,1):0;
    ?>
<div class="site-analytics-toolbar"><div><span>Site and listening intelligence</span><h2>Analytics dashboard</h2><p>Website behavior, conversion activity, Music Library listening, and visual-builder engagement in one view.</p></div><form method="get"><input type="hidden" name="view" value="site-analytics"><select name="days" onchange="this.form.submit()"><?php foreach([7,30,60,90,180,365] as $option):?><option value="<?=$option?>" <?=$days===$option?'selected':''?>>Last <?=$option?> days</option><?php endforeach;?></select></form></div>
<div class="analytics-stat-grid"><article><span>Unique visitors</span><strong><?=(int)$totals['visitors']?></strong><small><?=(int)$totals['sessions']?> sessions</small></article><article><span>Page views</span><strong><?=(int)$totals['page_views']?></strong><small><?=(int)$totals['events']?> tracked actions</small></article><article><span>Conversions</span><strong><?=(int)$totals['conversions']?></strong><small>Forms, bookings, intake, proposals</small></article><article><span>Listening starts</span><strong><?=$musicTotals['starts']?></strong><small><?=count($musicTotals['listeners'])?> unique listeners</small></article><article><span>Completion rate</span><strong><?=$completionRate?>%</strong><small><?=$musicTotals['completions']?> completed listens</small></article></div>
<div class="site-analytics-layout"><section class="panel"><header class="panel-header"><div><span>Website activity</span><h2>Top pages</h2></div></header><div class="table-wrap"><table><thead><tr><th>Page</th><th>Views</th><th>Visitors</th></tr></thead><tbody><?php foreach($topPages as $row):?><tr><td><?=e($row['page_path']?:'/')?></td><td><?=(int)$row['views']?></td><td><?=(int)$row['visitors']?></td></tr><?php endforeach;?><?php if(!$topPages):?><tr><td colspan="3">No page activity recorded in this period.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><header class="panel-header"><div><span>Music Library</span><h2>Listening behavior</h2></div></header><div class="music-analytics-summary"><article><span>Pauses</span><strong><?=$musicTotals['pauses']?></strong></article><article><span>Resumes</span><strong><?=$musicTotals['resumes']?></strong></article><article><span>Skips</span><strong><?=$musicTotals['skips']?></strong></article><article><span>Estimated listening</span><strong><?=e(call_center_seconds_label($musicTotals['seconds']))?></strong></article></div><div class="table-wrap"><table><thead><tr><th>Track</th><th>Starts</th><th>Completed</th><th>Skipped</th></tr></thead><tbody><?php foreach(array_slice($tracks,0,12) as $track):?><tr><td><?=e($track['title'])?></td><td><?=$track['starts']?></td><td><?=$track['completions']?></td><td><?=$track['skips']?></td></tr><?php endforeach;?><?php if(!$tracks):?><tr><td colspan="4">Listening activity will appear after v61 player events are recorded.</td></tr><?php endif;?></tbody></table></div><div class="music-album-analytics"><h3>Album activity</h3><?php foreach(array_slice($albums,0,6) as $album):?><article><strong><?=e($album['title'])?></strong><span><?=$album['starts']?> starts · <?=$album['completions']?> completed</span></article><?php endforeach;?><?php if(!$albums):?><p>No album activity yet.</p><?php endif;?></div></section></div>
<section class="panel"><header class="panel-header"><div><span>Event stream</span><h2>Recent music activity</h2></div></header><div class="music-event-stream"><?php foreach(array_slice($music,0,30) as $event):?><article><span class="status"><?=e(status_label(str_replace('music_track_','',$event['event_type'])))?></span><div><strong><?=e($event['event_label']?:'Music activity')?></strong><small><?=e($event['page_path']??'')?> · <?=e(format_datetime($event['occurred_at']))?></small></div><em><?=e(call_center_seconds_label((int)($event['duration_seconds']??0)))?></em></article><?php endforeach;?><?php if(!$music):?><p class="empty-state">No music activity recorded during this period.</p><?php endif;?></div></section>
<?php }
